const InterestData = [
  { key: "d1", name: "여행" },
  { key: "d2", name: "영화" },
  { key: "d3", name: "음악" },
  { key: "d4", name: "뮤지컬" },
  { key: "d8", name: "독서" },
  { key: "d5", name: "노래듣기" },
  { key: "d6", name: "노래부르기" },
  { key: "d7", name: "춤" },
  { key: "d9", name: "요리" },
  { key: "d10", name: "사진" },
  { key: "d11", name: "운동" },
  { key: "d12", name: "헬스" },
  { key: "d18", name: "자전거" },
  { key: "d13", name: "야구" },
  { key: "d15", name: "농구" },
  { key: "d14", name: "축구" },
  { key: "d16", name: "러닝" },
  { key: "d20", name: "산책" },
  { key: "d17", name: "수영" },
  { key: "d19", name: "보드게임" },
  { key: "d21", name: "악기연주" },
  { key: "d23", name: "외국어공부" },
  { key: "d24", name: "취업준비" },
  { key: "d25", name: "자격증" },
  { key: "d22", name: "고민상담" },
  { key: "d30", name: "드라마" },
  { key: "d27", name: "카페" },
  { key: "d31", name: "게임" },
  { key: "d26", name: "맛집" },
  { key: "d34", name: "패션" },
  { key: "d32", name: "애니메이션" },
  { key: "d28", name: "시사/정치" },
  { key: "d33", name: "반려동물" },
  { key: "d35", name: "다이어트" },
  { key: "d36", name: "메이크업" },
  { key: "d37", name: "재테크" },
  { key: "d38", name: "덕질" },
  { key: "d39", name: "종교" },
]

export default InterestData
